function infotext() {
    var mytitles = [ "Electric System",
        "Wings", 
        "Plane Fuselage",
        "Wing-Mounted Electric Engines",
        "T-Tail", // done
        "T-Tail", // done  
        "Tail-Mounted Turbo Jet-Engine, Exterior",
        "Pilots and Flight Systems",
        "Tail-Mounted Turbo Jet-Engine, Interior", //  
        "SUbsonic Single Aft eNgine (SUSAN) Aircraft"
        ]
    
    var myinfo = [
        // Electric system/wires
        "The tail-mounted turbofan engine provides thrust as well as the power to drive this 20 MW electric generator, which is then"+
        " transferred to the deistributed electric propulsors on the wings. The electric system also contains a gearbox, which allows"+
        " the turbofan engine to rotate at a lower speed and thus increase the efficiency. The main generator set consists of one 1 MW"+
        " 1 MW turbine control generator, followed by a four 5 MW generators.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210024573'>Explore publications on the power and engine systems.</a></br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025477'>Explore how aerodynamics can improve system efficiency and thrust.</a>",

        // Wings
        "The SUSAN aircraft has a wingspan of 118 ft. The wings have been designed for an 8.8% reduction in drag through studies"+
        " of the laminar flow, or smooth-traveling airflow, over the aircraft wings. Additionally, the wings are designed for an"+
        " efficient thermal management system with three loops at different temperatures that manage the engines, electrical system,"+
        " and batteries.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210024470'>Explore publications on SUSAN wing design and airflow.</a>",

        // Plane body
        "SUSAN is designed to accommodate up to 180 passengers (the same capacity as a large single-aisle plane)"+ 
        "and boasts a 10 MW class EAP system to electrify this regional-"+
        "class aircraft. The SUSAN concept was inspired by the idea that it may be possible to creat a transport category aircraft"+
        " with a single fuel burning engine if it is combined in a hybrid configuration with electric engines and an electrical"+
        " power source.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025477'>Explore the SUSAN concept design process.</a>",

        // wing-mounted electric engines
        "The wing-mounted engines provide 65% of the total thrust of the aircraft and are entirely electric. They draw from the" +
        " power generated by the tail-mounted turbo jet engine through the generators and the rechargeable battery, and under" +
        " nominal conditions the entire system is self-sufficient. The electric engines on either side of the plane are encased in" +
        " an outer shell to reduce drag from the suction effect of the fanblades.</br></br>"+
        "Each wing-mounted electric engine has a system"+
        " with a main generator converter, a rechargeable battery, a single use battery for emergency purposes, the electric engine"+
        " motor, and circuitry.</br></br>" +
        "<a href='https://ntrs.nasa.gov/citations/20210025440'>Explore publications on the engine and propulsion system.</a>",

        // T-tail
        "The vertical tail features an innovative design in which the structure is partially embedded in the exterior of the"+
        " engine and the primary loads are shared between the tail and the engine. This design also minimizes engine flow blockage,"+
        " and was tested to optimize airflow along the body of the plane.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025462'>Explore publications on the SUSAN aerodynamic design and airflow.</a>",

        // T-tail 2
        "The vertical tail features an innovative design in which the structure is partially embedded in the exterior of the"+
        " engine and the primary loads are shared between the tail and the engine. This design also minimizes engine flow blockage,"+
        " and was tested to optimize airflow along the body of the plane.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025462'>Explore publications on the SUSAN aerodynamic design and airflow.</a>",

        //engine protective sheath
        "The tail-mounted engine combines a traditional gas turbine with a mechanic called boundary Layer Ingesting (BLI)" +
        " concept, that uses the flow along the body of the plane to produce the required thrust. It uses hydrocarbon fuel to" +
        " to provide 35% of the total thrust for the aircraft and generates the power required for the wing-mounted electic" +
        " propulsors. The power is extracted and managed via generators and a rechargeable battery connected at the front of the" +
        " engine to the wing-mounted propulsors. In case of turbofan failure a single-use battery is employed.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025440'>Explore publications on the engine and propulsion system.</a>",

        //cockpit
        "The team behind the SUSAN project continue to develop a flight simulation system to improve the cockpit and aircraft"+
        " and receive pilot feedback. Due to the complexity of electrified aircraft, the information displayed to the pilot will"+
        " necessarily include additional variables beyond those of a standard cockpit.</br></br>"+
        "<a href='https://ntrs.nasa.gov/citations/20210025324'>Explore publications on the integrated systems of the aircraft.</a>",

         //engine back
         "The tail-mounted engine combines a traditional gas turbine with a mechanic called boundary Layer Ingesting (BLI)" +
         " concept, that uses the flow along the body of the plane to produce the required thrust. It uses hydrocarbon fuel to" +
         " to provide 35% of the total thrust for the aircraft and generates the power required for the wing-mounted electic" +
         " propulsors. The power is extracted and managed via generators and a rechargeable battery connected at the front of the" +
         " engine to the wing-mounted propulsors. In case of turbofan failure a single-use battery is employed.</br></br>"+
         "<a href='https://ntrs.nasa.gov/citations/20210025440'>Explore publications on the engine and propulsion system.</a>",

        //default
        "NASA’s SUbsonic Single Aft eNgine (SUSAN) Electrofan is an advanced hybrid electric concept aircraft that could transform"+
        " the future of commercial air travel by reducing fuel burn and improving performance. Take a look around and explore some of"+
        " the unique features onboard the aircraft.</br></br>" +
        "Navigate by clicking on the parts of the aircraft you wish to learn more about.",
    ]

    /*
    <div style="max-width: 854px; max-height: 1000px">
        <div style="height: 850;padding-bottom: 0">
            <iframe src="https://www.grc.nasa.gov/WWW/GVIS/%F0%9F%A7%AA/SUSAN/SUSANthumbnail.html" width="745" height="610" scrolling="no"></iframe>
        </div>
        <a href="https://www.grc.nasa.gov/WWW/GVIS/%F0%9F%A7%AA/SUSAN/SUSANembed.html" target="_blank">Click here for fullscreen.</a>
    </div>
    */

    return { "mytitles": mytitles, "myinfo": myinfo };
}

export { infotext };